### ISSUE TITLE
Blists Hill 'information' query

### ISSUE THREAD

**Issue by PeteCollins** [blackradley/nesscliffe#37]
Dear Pete,
Many thanks for the prompt response and useful further information. Regarding the small ‘i’, when I click on it nothing happens, any idea what I’m not doing right?!

- Have requested browser/operating system info/screenshot.

**Comment by PeteCollins** [comment]
Dear Pete,
I have just had out IT chap over and he has updated me to Internet Explorer 11 and all is now working fine – I was previously running on Internet Explorer 8. My operating system is Windows 7.
Many thanks,
Barbara.

**Comment by joejcollins** [comment]
A test https://saucelabs.com/tests/8a2f18776d35498286ed2b12b732335c shows the same effect at 1:45.  I'll see if we are missing some kind of shim or polyfill that might fix this.

**Comment by joejcollins** [comment]
The tool tips at http://getbootstrap.com/javascript/#tooltips work.  It might be to do with the Span inside the Anchor http://stackoverflow.com/questions/13246818/title-tooltip-is-not-shown-when-span-is-child-of-anchor  I tried the recommended fix but no result.  The cycle time for testing is too long because we have to deploy and then test with SauceLabs, so I am going to close this one.
